title: Wang Zesong # your name (or website title) here
logo: "imgaes/WechatIMG66.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Engineering, NUS, 2019-2023
  <br><br>
  <a href="https://www.linkedin.com/in/zesong-wang-8b497a181/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
